// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "An example SnapServe plugin",
  "name": "SnapServe Wonka Plugin",
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 2,
    "revision": 3,
    "text": "0.1.2",
    "timestamp": 1722140326
  },
  "stack": {
    "nodejs": {
      "outputFile": [
        "cinnabar.js"
      ],
      "package": "snapserve-wonka"
    }
  }
};
